# syntax=docker/dockerfile:1
# If you have issues with the base meltano file, this should work

FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install -y -q \
    gcc \
    sqlite3 \
    libsqlite3-dev \
    python3 \
    python3-pip \
    python3-venv 

WORKDIR /project

# Set db environment variable
# ARG MELTANO_DATABASE_URI                                                                                                     
# ENV MELTANO_DATABASE_URI=postgresql://<user>:<password>@<host>:<port>/<db>

# Set environment variables for frontend
ENV MELTANO_UI_SESSION_COOKIE_SECURE=true
ENV MELTANO_UI_FORWARDED_ALLOW_IPS="*"
ENV FORWARDED_ALLOW_IPS="*"

# Install any additional requirements
COPY ./requirements.txt . 
RUN pip3 install -r requirements.txt

# Copy meltano files 
COPY ./meltano.yml . 
COPY ./tap-smoke-test ./tap-smoke-test
# COPY ./output ./output

# Install all plugins into the `.meltano` directory
RUN meltano install

# Pin `discovery.yml` manifest by copying cached version to project root
RUN cp -n .meltano/cache/discovery.yml . 2>/dev/null || :

# Don't allow changes to containerized project files, rather make changes in the 
ENV MELTANO_PROJECT_READONLY 1

# Copy over remaining project files
COPY . .

# Smoke test
RUN mkdir output
RUN meltano elt tap-smoke-test target-jsonl

# Expose the Meltano port
EXPOSE 5000

ENTRYPOINT ["meltano"]

